# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f364bb7c7a49c3d2a475c469bbff5178622ef3e3607c4fba1ab0e2b6c27bf433b4a67d9c7d373d5bc606f7a0567548c2dfbb224a2dea85049808d1e746252f34

test:
  secret_key_base: 4294478379b70dd2f7281f482ce0a0e3b9c9d500002b07cf2c9e7f0e0b413cf2f2518accd26571acbb989251c0f58892e55be6b3da1f774db451c41c7ec4e84a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
